# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, blazeHtml, fetchgit, happstackServer, mtl }:

cabal.mkDerivation (self: {
  pname = "cgroups-webapp";
  version = "0.1.0.1";
  src = fetchgit {
    url = "https://github.com/adrianmay/cgroups-webapp.git";
    sha256 = "8ebcb51ba98b4b13bb55a6a7dd6751d4cfba17c4426f76e2d01b7c585118bb2f";
    rev = "7d852a943fe64e768a25e8812b6c30597f5f87ab";
  };
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ blazeHtml happstackServer mtl ];
  meta = {
    description = "Browse and manipulate cgroups via http";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
